version: '2'
services:
    mongo:
      image: mongo:latest
      volumes:
        - ./run/db_path:/data/db
      expose: 
        - "27017"

    web:
      build:
        context: .
        args:
          CONFIG_FILE: config/app-docker.cfg
      restart: always
      volumes:
        - ./config:/webapps/sarjalipputasku/config:ro
        - ./backend:/webapps/sarjalipputasku/source:ro
        - ./frontend:/webapps/sarjalipputasku/static:ro
      expose:
        - "8000"
      depends_on:
        - mongo

    nginx:
      image: nginx:latest
      ports:
        - "8888:80"
      volumes:
        - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./frontend:/usr/share/nginx/html:ro 
      depends_on:
        - web
