FROM python:3.5.3
ARG CONFIG_FILE
ENV SARJALIPPUTASKU_DIR /webapps/sarjalipputasku
ENV SARJALIPPUTASKU_CONFIG_DIR $SARJALIPPUTASKU_DIR/config
ENV SARJALIPPUTASKU_CONFIGFILE $SARJALIPPUTASKU_CONFIG_DIR/app.cfg
ENV SARJALIPPUTASKU_SOURCE_DIR $SARJALIPPUTASKU_DIR/source
ENV PYTHONUNBUFFERED 1
RUN apt-get update && apt-get install -y libldap2-dev libsasl2-dev poppler-utils
RUN mkdir -p $SARJALIPPUTASKU_SOURCE_DIR
ADD backend $SARJALIPPUTASKU_SOURCE_DIR
ADD frontend $SARJALIPPUTASKU_SOURCE_DIR/static
ADD $CONFIG_FILE $SARJALIPPUTASKU_CONFIGFILE
WORKDIR $SARJALIPPUTASKU_SOURCE_DIR
ADD ./docker-entrypoint.sh /
RUN pip install -r requirements.txt
RUN pip install gunicorn
EXPOSE 8000
ENTRYPOINT ["sh", "/docker-entrypoint.sh"]
